# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SIzRHChsa6Z8DFTYCUHMGJuq89PEJ7km
"""

import pandas as pd
import random
import os
import streamlit as st

# Input Excel file with all names
input_file = "Book1.xlsx"
# Output Excel file to store picked names
picked_file = "picked_names.xlsx"

# Load all names
df = pd.read_excel(input_file)
names = df["Name"].tolist()

# Load already picked names if file exists
if os.path.exists(picked_file):
    picked_df = pd.read_excel(picked_file)
    picked_names = picked_df["Picked"].tolist()
else:
    picked_names = []

# Remove already picked names from available pool
names = [n for n in names if n not in picked_names]

st.title("Tambola Name Picker 🎲")

if st.button("Pick Name"):
    if not names:
        st.success("🎉 All names have been picked!")
    else:
        chosen = random.choice(names)
        picked_names.append(chosen)
        names.remove(chosen)

        # Save picked names
        pd.DataFrame({"Picked": picked_names}).to_excel(picked_file, index=False)

        st.subheader(f"👉 Selected: **{chosen}**")

st.write("### Picked so far:")
for i, name in enumerate(picked_names, start=1):
    st.write(f"{i}. {name}")