# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SIzRHChsa6Z8DFTYCUHMGJuq89PEJ7km
"""
import pandas as pd
import random
import os
import streamlit as st

# Input CSV file with all names
input_file = "Book1.csv"
# Output CSV file to store picked names
picked_file = "picked_names.csv"

# Load all names
df = pd.read_csv(input_file)
names = df["Name"].tolist()

# Load already picked names if file exists
if os.path.exists(picked_file):
    picked_df = pd.read_csv(picked_file)
    picked_names = picked_df["Picked"].tolist()
else:
    picked_names = []

# Remove already picked names from available pool
names = [n for n in names if n not in picked_names]

st.set_page_config(page_title="Tambola Picker", page_icon="🎲", layout="wide")
st.title("🎲 Tambola Name Picker")

# ---------------- Buttons ---------------- #
col_btn1, col_btn2 = st.columns(2)

with col_btn1:
    if st.button("Pick Name"):
        if not names:
            st.success("🎉 All names have been picked!")
        else:
            chosen = random.choice(names)
            picked_names.append(chosen)
            names.remove(chosen)

            # Save picked names
            pd.DataFrame({"Picked": picked_names}).to_csv(picked_file, index=False)

with col_btn2:
    if st.button("Reset Game"):
        if os.path.exists(picked_file):
            os.remove(picked_file)
        picked_names = []
        names = df["Name"].tolist()
        st.warning("⚠️ Game has been reset! All names are available again.")

# ---------------- Function to generate random color ---------------- #
def random_color():
    r = random.randint(100, 255)
    g = random.rand
