# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SIzRHChsa6Z8DFTYCUHMGJuq89PEJ7km
"""

import pandas as pd
import random
import os
import streamlit as st

# Input CSV file with all names
input_file = "Book1.csv"
# Output CSV file to store picked names
picked_file = "picked_names.csv"

# Load all names
df = pd.read_csv(input_file)
names = df["Name"].tolist()

# Load already picked names if file exists
if os.path.exists(picked_file):
    picked_df = pd.read_csv(picked_file)
    picked_names = picked_df["Picked"].tolist()
else:
    picked_names = []

# Remove already picked names from available pool
names = [n for n in names if n not in picked_names]

st.set_page_config(page_title="Tambola Picker", page_icon="🎲", layout="wide")
st.title("🎲 Tambola Name Picker")

# Pick Name Button
if st.button("Pick Name"):
    if not names:
        st.success("🎉 All names have been picked!")
    else:
        chosen = random.choice(names)
        picked_names.append(chosen)
        names.remove(chosen)

        # Save picked names
        pd.DataFrame({"Picked": picked_names}).to_csv(picked_file, index=False)

# Generate random bright color for highlight
def random_color():
    r = random.randint(100, 255)
    g = random.randint(100, 255)
    b = random.randint(100, 255)
    return f'rgb({r},{g},{b})'

# Create two columns: left for last picked, right for picked so far
col1, col2 = st.columns([2, 1])  # Left column bigger

with col1:
    if picked_names:
        color = random_color()
        st.markdown(
            f"<h1 style='text-align: left; background-color: {color}; padding: 20px; border-radius: 10px;'>{picked_names[-1]}</h1>",
            unsafe_allow_html=True
        )
    else:
        st.write("Click 'Pick Name' to start!")

with col2:
    st.write("### 📋 Picked so far:")
    if picked_names:
        for i, name in enumerate(picked_names, start=1):
            st.write(f"{i}. {name}")
    else:
        st.info("No names picked yet.")
